version: "3.3"
services:
  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    container_name: "shader-sandbox"
    volumes:
      - .:/var/www/html
      - ./docker/log/nginx:/var/log/nginx
    environment:
      - VIRTUAL_HOST=shader.toutounode.com
      - LETSENCRYPT_HOST=shader.toutounode.com
networks:
  default:
    external:
      name: toutou_shared
